spring:
  config:
    activate:
      on-profile: test
  liquibase:
    enabled: true
    change-log: classpath:db_changelog.yaml
  datasource:
    url: "jdbc:postgresql://localhost:5432/MTS Credit App TESTS"
    driver-class-name: org.postgresql.Driver
    username: user
    password: 12345
