spring:
  config:
    activate:
      on-profile: test
  liquibase:
    enabled: true
    change-log: classpath:db_changelog.yaml
  datasource:
    url: "jdbc:postgresql://localhost:5432/MTS_Credit_App_TESTS"
    driver-class-name: org.postgresql.Driver
    username: user
    password: 1234

fixedRate: 5000
initialDelay: 5000
waitingTime: 5000