INSERT INTO TARIFF(TYPE, INTEREST_RATE)
SELECT 'BUSINESS', '2%'
WHERE NOT EXISTS(SELECT * FROM TARIFF WHERE TYPE = 'BUSINESS');

INSERT INTO TARIFF(TYPE, INTEREST_RATE)
SELECT 'CONSUMER', '10%'
WHERE NOT EXISTS(SELECT * FROM TARIFF WHERE TYPE = 'CONSUMER');

INSERT INTO TARIFF(TYPE, INTEREST_RATE)
SELECT 'RETIRED', '4%'
WHERE NOT EXISTS(SELECT * FROM TARIFF WHERE TYPE = 'RETIRED');